#### Data Cleaning

In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/car_price_dataset.csv")

df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [3]:
#Remove the Unnamed column
df.drop("Unnamed: 0", axis=1, inplace=True)

In [6]:
df.columns.to_list()

['car_name',
 'brand',
 'model',
 'vehicle_age',
 'km_driven',
 'seller_type',
 'fuel_type',
 'transmission_type',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price']

In [7]:
df.duplicated().sum()

np.int64(167)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (15244, 13)

In [10]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [17]:
df.dtypes

car_name                 str
brand                    str
model                    str
vehicle_age            int64
km_driven              int64
seller_type              str
fuel_type                str
transmission_type        str
mileage              float64
engine                 int64
max_power            float64
seats                  int64
selling_price          int64
dtype: object

In [18]:
print("Mileage:")
print(df['mileage'].head(10))

print("\nEngine:")
print(df['engine'].head(10))

Mileage:
0    19.70
1    18.90
2    17.00
3    20.92
4    22.77
5    18.90
6    20.36
7    20.51
8    18.15
9    16.60
Name: mileage, dtype: float64

Engine:
0     796
1    1197
2    1197
3     998
4    1498
5     998
6    1197
7     998
8     998
9    1197
Name: engine, dtype: int64

In [19]:
print("\nMax Power:")
print(df['max_power'].head(10))

Max Power:
0     46.30
1     82.00
2     80.00
3     67.10
4     98.59
5     67.10
6     78.90
7     67.04
8    118.35
9     85.00
Name: max_power, dtype: float64

In [14]:
df["selling_price"].describe()

count    1.524400e+04
mean     7.747014e+05
std      8.946761e+05
min      4.000000e+04
25%      3.850000e+05
50%      5.590000e+05
75%      8.250000e+05
max      3.950000e+07
Name: selling_price, dtype: float64

In [15]:
df["selling_price"].sort_values().head(10)

7607     40000
13676    45000
7361     50000
3787     50000
12298    50000
7930     55000
2596     60000
11190    60000
2966     60000
9045     60000
Name: selling_price, dtype: int64

In [16]:
df["selling_price"].sort_values(ascending=False).head(10)

3799     39500000
10969    24200000
1172     14500000
9722     13000000
9364     11100000
1888     11000000
10989    11000000
11000     9200000
8439      8500000
3096      8500000
Name: selling_price, dtype: int64

In [20]:
df.nlargest(20, "selling_price")[
    ["car_name", "brand", "model", "vehicle_age",
     "km_driven", "fuel_type", "transmission_type",
     "engine", "max_power", "selling_price"]
]

,car_name,brand,model,vehicle_age,km_driven,fuel_type,transmission_type,engine,max_power,selling_price
3799,Ferrari GTC4Lusso,Ferrari,GTC4Lusso,2,3800,Petrol,Automatic,3855,601.00,39500000
10969,Rolls-Royce Ghost,Rolls-Royce,Ghost,4,5000,Petrol,Automatic,6592,563.00,24200000
1172,Bentley Continental,Bentley,Continental,9,9000,Petrol,Automatic,5998,626.00,14500000
9722,Mercedes-Benz S-Class,Mercedes-Benz,S-Class,3,4000,Petrol,Automatic,4663,459.00,13000000
9364,Porsche Cayenne,Porsche,Cayenne,4,24000,Petrol,Automatic,3604,440.00,11100000
1888,Mercedes-Benz S-Class,Mercedes-Benz,S-Class,5,41000,Petrol,Automatic,5461,362.90,11000000
10989,Mercedes-Benz S-Class,Mercedes-Benz,S-Class,2,18000,Petrol,Automatic,2996,362.07,11000000
11000,Land Rover Rover,Land Rover,Rover,4,9500,Diesel,Automatic,2993,296.00,9200000
3096,BMW 7,BMW,7,3,50000,Diesel,Automatic,2993,261.49,8500000
8439,BMW 7,BMW,7,3,19000,Diesel,Automatic,2993,355.37,8500000
311,BMW Z4,BMW,Z4,1,2000,Petrol,Automatic,2998,335.00,8250000
8806,BMW 7,BMW,7,3,16000,Diesel,Automatic,2993,261.49,8200000
11541,Volvo XC,Volvo,XC,1,9000,Diesel,Automatic,1969,235.00,8195000
3410,Mercedes-Benz S-Class,Mercedes-Benz,S-Class,4,6500,Diesel,Automatic,2987,254.79,8150000
10403,BMW X5,BMW,X5,2,10000,Diesel,Automatic,2993,265.00,8100000
12827,BMW X5,BMW,X5,2,10351,Diesel,Automatic,2993,265.00,8100000
12997,Bentley Continental,Bentley,Continental,10,30000,Petrol,Automatic,5998,552.00,8100000
10459,Volvo XC,Volvo,XC,1,9500,Diesel,Automatic,1969,235.00,8000000
14167,Lexus RX,Lexus,RX,5,17272,Petrol,Automatic,3456,259.00,8000000
15251,Mercedes-Benz GLS,Mercedes-Benz,GLS,3,15000,Diesel,Automatic,2987,258.00,8000000

In [21]:
df["selling_price"].quantile([0.90, 0.95, 0.99, 0.995, 0.999])

0.900    1375000.0
0.950    2050000.0
0.990    4528500.0
0.995    5748495.0
0.999    8100000.0
Name: selling_price, dtype: float64

In [23]:
df.nlargest(10, "selling_price")[["car_name", "selling_price"]]

                    car_name  selling_price
3799       Ferrari GTC4Lusso       39500000
10969      Rolls-Royce Ghost       24200000
1172     Bentley Continental       14500000
9722   Mercedes-Benz S-Class       13000000
9364         Porsche Cayenne       11100000
1888   Mercedes-Benz S-Class       11000000
10989  Mercedes-Benz S-Class       11000000
11000       Land Rover Rover        9200000
3096                   BMW 7        8500000
8439                   BMW 7        8500000

In [26]:
df.shape

(15244, 13)

In [27]:
df.to_csv(
    "../data/processed/used_car_dataset_cleaned.csv",
    index=False
)